<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD" tests="29" failures="1" timestamp="01 May 2019 12:14:13 GMT" time="683.476" errors="6">
  <testcase name="gettingDataEPP" time="149.688" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.893" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.064" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.311" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.333" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="126.488" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.414" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.730" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.632" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.566" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="9.428" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.816" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.407" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.807" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="8.505" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.277" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.428" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:15)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="7.233" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.036" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.040" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="7.915" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.488" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.737" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <failure type="java.lang.AssertionError" message="expected [Maturity Instruction] but found [Renewal instruction]">
      <![CDATA[java.lang.AssertionError: expected [Maturity Instruction] but found [Renewal instruction]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:38)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="7.401" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="7.957" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="12.519" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:13)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD.gettingDataEPP(Test__EMEA_RU_AD_140_RegularTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="8.227" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="191.585" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
  <testcase name="gettingDataEPP" time="8.551" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD"/>
</testsuite> <!-- com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_RegularTD -->
