<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD" tests="29" failures="3" timestamp="01 May 2019 13:40:00 GMT" time="891.216" errors="0">
  <testcase name="gettingDataEPP" time="24.553" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="25.556" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="17.825" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="12.056" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="10.484" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="19.106" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="24.367" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="190.411" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="13.290" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="11.415" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="16.106" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="27.217" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD">
    <failure type="java.lang.AssertionError" message="expected [12 Month] but found [12 Months]">
      <![CDATA[java.lang.AssertionError: expected [12 Month] but found [12 Months]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:38)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD.gettingDataEPP(Test__EMEA_RU_AD_140_LadderTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="9.268" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="6.593" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="27.059" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="11.174" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="97.552" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="29.457" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="14.951" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="9.787" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD">
    <failure type="java.lang.AssertionError" message="expected [12 Month] but found [12 Months]">
      <![CDATA[java.lang.AssertionError: expected [12 Month] but found [12 Months]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:38)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD.gettingDataEPP(Test__EMEA_RU_AD_140_LadderTD.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="148.373" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="14.026" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="28.395" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="19.782" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="13.671" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="27.568" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD">
    <failure type="java.lang.AssertionError" message="expected [Maturity Instruction] but found [Renewal instruction]">
      <![CDATA[java.lang.AssertionError: expected [Maturity Instruction] but found [Renewal instruction]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:38)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD.gettingDataEPP(Test__EMEA_RU_AD_140_LadderTD.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="11.309" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="14.062" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
  <testcase name="gettingDataEPP" time="15.803" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD"/>
</testsuite> <!-- com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_140_LadderTD -->
