<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RDT039" name="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities" tests="32" failures="4" timestamp="01 May 2019 20:16:37 GMT" time="1059.669" errors="1">
  <testcase name="gettingDataEPP" time="45.207" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities">
    <error type="org.openqa.selenium.TimeoutException" message="Timed out after 20 seconds waiting for presence of element located by: By.xpath: //android.widget.TextView[@resource-id=&quot;com.citibank.mobile.ru.dit:id/label&quot;][2]
Build info: version: &#039;2.45.0&#039;, revision: &#039;5017cb8e7ca8e37638dc3091b2440b90a1d8686f&#039;, time: &#039;2015-02-27 09:10:26&#039;
System info: host: &#039;RDT039&#039;, ip: &#039;192.168.1.15&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_201&#039;
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK&#039;s\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, desired={app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK&#039;s\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 8670bb98-7a9b-41ab-9671-b8ceaeff092e">
      <![CDATA[org.openqa.selenium.TimeoutException: Timed out after 20 seconds waiting for presence of element located by: By.xpath: //android.widget.TextView[@resource-id="com.citibank.mobile.ru.dit:id/label"][2]
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'RDT039', ip: '192.168.1.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK's\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, desired={app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK's\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 8670bb98-7a9b-41ab-9671-b8ceaeff092e
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:79)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at com.citi.mobileAutomation.utils.ResuableFunction.getTextFromElementByWait(ResuableFunction.java:183)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:37)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities.gettingDataEPP(Test__EMEA_RU_AD_100_Securities.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.08 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'RDT039', ip: '192.168.1.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities [{app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK's\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, deviceScreenSize=1440x2560, networkConnectionEnabled=true, warnings={}, databaseEnabled=false, deviceName=emulator-5554, platform=LINUX, deviceUDID=emulator-5554, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, desired={app=C:\Users\admin\Desktop\RU code\Citi_EMEA_CrossCountries\ListOfAPK's\tcsios_TW_JAN_M63_SIT_H35.apk, appPackage=com.citibank.mobile.ru.dit, appActivity=com.citi.mobile.pt3.starter.authentication.view.activity.LoginActivity, androidInstallTimeout=150000, platformVersion=8.1.0, skipUnlock=true, autoGrantPermissions=true, platformName=Android, deviceName=emulator-5554}, platformVersion=8.1.0, webStorageEnabled=false, locationContextEnabled=false, takesScreenshot=true, skipUnlock=true, autoGrantPermissions=true, javascriptEnabled=true, deviceModel=Android SDK built for x86, platformName=Android, deviceManufacturer=Google}]
Session ID: 8670bb98-7a9b-41ab-9671-b8ceaeff092e
*** Element info: {Using=xpath, value=//android.widget.TextView[@resource-id="com.citibank.mobile.ru.dit:id/label"][2]}
at sun.reflect.GeneratedConstructorAccessor32.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:51)
at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:449)
at io.appium.java_client.DefaultGenericMobileDriver.findElementByXPath(DefaultGenericMobileDriver.java:145)
at io.appium.java_client.AppiumDriver.findElementByXPath(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElementByXPath(AndroidDriver.java:1)
at org.openqa.selenium.By$ByXPath.findElement(By.java:357)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:730)
at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:39)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:106)
at org.openqa.selenium.support.ui.ExpectedConditions$3.apply(ExpectedConditions.java:103)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
... 29 more
]]>
    </error>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="15.049" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.870" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="23.958" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.789" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="33.288" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities">
    <failure type="java.lang.AssertionError" message="expected [ SGIS 3Y USD DAILY RA NOTE (1928, MPEL &amp; 2318) DUE 29AUG2017] but found []">
      <![CDATA[java.lang.AssertionError: expected [ SGIS 3Y USD DAILY RA NOTE (1928, MPEL & 2318) DUE 29AUG2017] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:34)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities.gettingDataEPP(Test__EMEA_RU_AD_100_Securities.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="5.694" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="30.832" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.630" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="26.500" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="19.896" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="24.630" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="45.433" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:13)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:75)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities.gettingDataEPP(Test__EMEA_RU_AD_100_Securities.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="18.612" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.623" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities">
    <failure type="java.lang.AssertionError" message="expected [Notes] but found [Securities]">
      <![CDATA[java.lang.AssertionError: expected [Notes] but found [Securities]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:34)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities.gettingDataEPP(Test__EMEA_RU_AD_100_Securities.java:23)
at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="6.459" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="29.988" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.212" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="28.279" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities">
    <failure type="java.lang.AssertionError" message="expected [-25.11%] but found []">
      <![CDATA[java.lang.AssertionError: expected [-25.11%] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.citi.mobileAutomation.assertEngine.Assert_Engine.assertMapping(Assert_Engine.java:9)
at com.citi.mobileAutomation.dataMapping.Action_Mapping.actionMapping_Mobile_Application_Native_Android(Action_Mapping.java:34)
at com.citi.mobileAutomation.dataMapping.ObjectGroups.actionOnElements(ObjectGroups.java:59)
at com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities.gettingDataEPP(Test__EMEA_RU_AD_100_Securities.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- gettingDataEPP -->
  <testcase name="gettingDataEPP" time="245.794" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="24.040" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="13.261" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="6.450" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="29.478" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="183.154" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="91.102" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="40.154" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="8.098" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.776" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="5.830" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="7.294" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
  <testcase name="gettingDataEPP" time="17.289" classname="com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities"/>
</testsuite> <!-- com.citi.mobileAutomation.test_RU.Test__EMEA_RU_AD_100_Securities -->
